language: python
python:
    - "2.7"
env:
    - DJANGO=1.5.5
before_install:
    - sudo apt-get install -y libevent-dev
install: pip install -r requirements.txt
before_script:
    - npm install # until travis supports multi-language: https://groups.google.com/forum/#!topic/travis-ci/3pzCgvxWZAo
script:
    - coverage run manage.py test --settings=mycarhistory.settings.test
    - karma start --single-run 

