language: python
python:
    - "2.7"
env:
    - DJANGO=1.6
before_install:
    - sudo apt-get install -y libevent-dev
install: pip install -r requirements.txt
before_script:
    # until travis supports multi-language: https://groups.google.com/forum/#!topic/travis-ci/3pzCgvxWZAo
    - npm install grunt-cli
    - npm install bower
    - cd frontend
    - bower install
    - cd ..
script:
    - coverage run manage.py test --settings=mycarhistory.settings.test
    - cd frontend
    - grunt test:ci
    - cd ..

