language: python
python:
    - "2.7"
env:
    - DJANGO=1.5.4
before_install: 
    - git submodule update --init
install: pip install -r requirements-dev.txt
script: coverage run manage.py test --settings=mycarhistory.settings.test
