language: python
python:
    - "2.7"
env:
    - DJANGO=1.5.5
 before_install:
     - sudo apt-get install -y libevent-dev
install: pip install -r requirements-dev.txt
script: coverage run manage.py test --settings=mycarhistory.settings.test
